[project]
name = "fasthtml-shadcn-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-fasthtml>=0.12.16",
    "shad4fast>=1.3.1",
]
